[package]
name = "interfacing-with-c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [target.release]
# rustflags = ["-C", "link-args=-Lsimple-adder/src"]

[dependencies]
